language: python
python:
 - "2.7"

services: mongodb

install:
 - pip install -r requirements.txt

script:
 - python NoInventory/test_item.py
 - python NoInventory/test_inventario.py


after_deploy:
  - python manage.py syncdb --noinput
  
    
