db:
  image: sameersbn/mongodb:latest
web:
  image: hugobarzano/noinventory:latest
  command: sh -c "cd /NoInventory && python manage.py makemigrations --noinput"
  command: sh -c "cd /NoInventory && python manage.py migrate --noinput"
  command: sh -c "cd /NoInventory && python manage.py syncdb --noinput"
  command: sh -c "ifconfig && cd /NoInventory && sudo python manage.py runserver 0.0.0.0:80"

  ports:
    - "80:80"
    - "27017:27017"
  links:
    - db
  environment:
    - COMPOSE=true
