db:
  image: hugobarzano/noinventory:mongo

  #command: sh -c "sudo service mongodb restart"

  ports:
    - "27017:27017"

  #command: sh -c "cd /etc/ && ls -la"
  #command: sh -c "iptables -A INPUT -p tcp --dport 27017 -j ACCEPT"

  #command: sh -c "ls -la ~/"
  #command: sh -c "sed -i 's/^bind_ip = 127.0.0.1/bind_ip = 0.0.0.0/g' /etc/mongod.conf"
  #command: sh -c "sudo -i echo bind_ip = 0.0.0.0 >> /etc/mongod.conf.orig"
  #command: sh -c "sed 's/bind_ip = 127.0.0.1/#bind_ip = 127.0.0.1/g'  /etc/mongod.conf.orig"
  #command: sh -c "cd /etc/ && cat mongod.conf.orig"


web:
  image: hugobarzano/noinventory:latest
  command: sh -c "cd /NoInventory && python manage.py makemigrations --noinput"
  command: sh -c "cd /NoInventory && python manage.py migrate --noinput"
  command: sh -c "cd /NoInventory && python manage.py syncdb --noinput"
  command: sh -c "ifconfig && cd /NoInventory && sudo python manage.py runserver 0.0.0.0:80"

  ports:
    - "80:80"
  links:
    - db
  environment:
    - COMPOSE=true
